# Generated by Django 4.0.1 on 2022-01-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(null=True)),
                ('apellidos', models.TextField(null=True)),
                ('telefono', models.IntegerField(max_length=9)),
                ('email', models.TextField(null=True)),
                ('comentario', models.TextField(null=True)),
            ],
        ),
    ]
